#!/usr/bin/env bash
# Displays "bad luck" at 4, "good luck" at 8, "Best School" elsewhere

i=0
while [[ i -lt 8 ]]
do
 echo "Best School"
 i=$(( i + 1 ))
 if [ $i == 3 ]
 then
  echo "bad luck"

 elif [ $i == 6 ]
 then
  echo "good luck"

 else
  continue
 fi
done
