#!/usr/bin/env bash
# Print "bad luck- China 4, Japan 9, Italy 17", number

i=0
while [[ i -lt 20 ]]
do
 i=$(( i + 1 ))
 case $i in 
     4)
	 echo "$i"
	 echo "bad luck from China"
	 ;;
     9) 
	 echo "$i"
	 echo "bad luck from Japan"
	 ;;
     17)
         echo "$i"
         echo "bad luck from Italy"
	 ;;
     *)
         echo "$i"
	 ;;
 esac
done
