#!/usr/bin/env bash
# Check if file exists then display info

if ! [ -f school ]
then
	if [ -d school ]
	then
		echo "school file exists"
		echo "school file is not empty"
	else
		echo "school file does not exist"
	fi
else
	echo "school file exists"

	size=$(stat -c %s school)
	result=$(stat -c %F school)
	if [ "$size" == "0" ]
	then
		echo "school file is empty"
		if [ "$result" == "regular empty file" ]
		then
			echo "school is a regular file"
		fi
	else
		echo "school file is not empty"
		if [ "$result" == "regular file" ]
		then
			echo "school is a regular file"
		fi
	fi
fi
